### ISSUE TITLE
App not build

### ISSUE THREAD

**Issue by Sahcode01** [webrror/watchos_flutter_test#1]
I keep getting:
Launching lib/main.dart on Watch SE in debug mode...
Upgrading AppFrameworkInfo.plist
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Adding input path to Thin Binary build phase.
Watch companion app found.
Xcode build done.                                            3.7s
Failed to build iOS app
Uncategorized (Xcode): Failed to build workspace Runner with scheme Runner.

Could not build the application for the simulator.
Error launching application on Watch SE.

Exited (1).

**Comment by webrror** [comment]
It seems you're trying to run the app directly on the Watch. This won't work because watch apps are native extensions and need to be launched through Xcode.

First of all here's my output of `flutter doctor`:

`[✓] Flutter (Channel stable, 3.19.0, on macOS 14.4 23E214 darwin-arm64, locale en-IN)`
`[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)`
`[✓] Xcode - develop for iOS and macOS (Xcode 15.3)`
`[✓] Chrome - develop for the web`
`[✓] Android Studio (version 2023.2)`
`[✓] VS Code (version 1.87.0)`

Here's a quick video as to how I run this app.

https://github.com/webrror/watchos_flutter_test/assets/65507007/4cdae697-8638-4e9e-91ac-7f571e56f97a


Let me know if you have anymore questions.

**Comment by webrror** [comment]
Closing this issue for now
